# -*- coding: utf-8 -*-
"""REVENUE_TRANSACTIONS.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1P-ZFyXEkMSUiFlbP8y7EnMUh-rQpjfZ8
"""

import pandas as pd
import numpy as np

df=pd.read_csv("/content/revenue_transactions.csv")

df.head()

df["expected_revenue"] = df["list_price"] * df["quantity"]
df["actual_revenue"] = df["final_price"] * df["quantity"]
df["revenue_leakage"] = df["expected_revenue"] - df["actual_revenue"]

total_revenue = df.loc[df["payment_status"] == "Success", "actual_revenue"].sum()
total_leakage = df["revenue_leakage"].sum()
leakage_pct = (total_leakage / total_revenue) * 100

leakage_by_plan = (
    df.groupby("plan")["revenue_leakage"]
      .sum()
      .reset_index()
      .sort_values(by="revenue_leakage", ascending=False)
)

leakage_by_region = (
    df.groupby("region")["revenue_leakage"]
      .sum()
      .reset_index()
      .sort_values(by="revenue_leakage", ascending=False)
)

customer_leakage = (
    df.groupby("customer_id")["revenue_leakage"]
      .sum()
      .reset_index()
      .sort_values(by="revenue_leakage", ascending=False)
)

customer_leakage["cumulative_pct"] = (
    customer_leakage["revenue_leakage"].cumsum()
    / customer_leakage["revenue_leakage"].sum()
)

leakage_by_plan.to_csv("leakage_by_plan.csv", index=False)
leakage_by_region.to_csv("leakage_by_region.csv", index=False)
customer_leakage.to_csv("customer_leakage_pareto.csv", index=False)

import os
os.getcwd()

from google.colab import files

files.download("leakage_by_plan.csv")
files.download("leakage_by_region.csv")
files.download("customer_leakage_pareto.csv")